project:
  type: website

website:
  title: "Samuel Gerken"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/SGerk5015
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-gerken/
format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css



